FROM registry.elandsystems.cn/golang:unit-test AS builder
RUN go get github.com/smartystreets/goconvey/convey
WORKDIR /go/src/go-api
COPY . .
# disable cgo
ENV CGO_ENABLED=0
# build steps
RUN echo ">>> 1: go version" && go version
RUN echo ">>> 2: go get" && go get -v -d
RUN echo ">>> 3: go test" && go test ./...
