FROM golang:1.13 AS builder

RUN go env -w GOPROXY=https://goproxy.cn,direct
WORKDIR /go/src/github.com/relax-space/go-api
ADD go.mod go.sum ./
RUN go mod download
ADD . /go/src/github.com/relax-space/go-api
ENV CGO_ENABLED=0
RUN go build -o go-api

FROM pangpanglabs/alpine-ssl
WORKDIR /go/src/github.com/relax-space/go-api
COPY --from=builder /go/src/github.com/relax-space/go-api/*.yml /go/src/github.com/relax-space/go-api/
COPY --from=builder /go/src/github.com/relax-space/go-api/go-api /go/src/github.com/relax-space/go-api/

EXPOSE 8080
CMD ["./go-api"]
